# RabbitMQ connexion
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Retry
rabbitmq.retry.max-attempts=3

# Queues
rabbitmq.queues.message=queue-message
rabbitmq.queues.message-dlq=queue-message.dlq

# Exchanges
rabbitmq.exchanges.message=exchange-message
rabbitmq.exchanges.dlq=exchange-message.dlq

# Routing keys
rabbitmq.routing-keys.message=routing-message
rabbitmq.routing-keys.dlq=routing-message.dlq

# Routing keys
spring.data.mongodb.uri=mongodb://localhost:27017/togezzer