spring.application.name=chat-sauvegarde

# RabbitMQ connexion
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# Retry
rabbitmq.retry.max-attempts=${RABBITMQ_RETRY_MAX_ATTEMPTS:3}

# Queues
rabbitmq.queues.message=${RABBITMQ_QUEUE_MESSAGE:queue-message-chat-sauvegarde}
rabbitmq.queues.message-dlq=${RABBITMQ_QUEUE_MESSAGE_DLQ:queue-message-chat-sauvegarde.dlq}

# Exchanges
rabbitmq.exchanges.message=${RABBITMQ_EXCHANGE_MESSAGE:exchange-message}
rabbitmq.exchanges.dlq=${RABBITMQ_EXCHANGE_DLQ:exchange-message.dlq}

# Routing keys
rabbitmq.routing-keys.message=${RABBITMQ_ROUTING_MESSAGE:routing-message-chat-sauvegarde}
rabbitmq.routing-keys.dlq=${RABBITMQ_ROUTING_DLQ:routing-message-chat-sauvegarde.dlq}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/togezzer}

# Server
server.port=${SERVER_PORT:8081}